// FIX: Added OrderLineItem to the import list to resolve 'Cannot find name' error.
import { Material, Vendor, User, InventoryItem, PurchaseOrder, Priority, OrderStatus, Site, MaterialIssuance, PurchaseIntent, PurchaseIntentStatus, OrderLineItem } from './types';

export const INITIAL_MATERIALS: Omit<Material, 'id'>[] = [
  { name: 'Plywood (18mm)', unit: 'sheets' },
  { name: 'Oak Veneer', unit: 'sq. ft.' },
  { name: 'Linen Fabric', unit: 'meters' },
  { name: 'Italian Marble', unit: 'sq. ft.' },
  { name: 'Wood Glue Agent', unit: 'liters' },
  { name: 'High-Density Foam', unit: 'sheets' },
  { name: 'Stainless Steel Hinges', unit: 'pieces' },
  { name: 'Matte Black Paint', unit: 'liters' },
];

export const UNITS: string[] = [
    'Bag', 'Box', 'Cubic. Ft.', 'Cubic. Mtr', 'Drum', 'Gram', 'Kg', 'liters', 'meters', 'Nos.', 'Pcs', 'pieces', 'Pkt', 
    'Roll', 'Running Ft.', 'Set', 'sheets', 'sq. ft.', 'Sq.Mtr', 'Tin'
];

export const INITIAL_VENDORS: Omit<Vendor, 'id'>[] = [
  { name: 'Royal Timbers Inc.' },
  { name: 'Fabricorp Textiles' },
  { name: 'Stone World Suppliers' },
  { name: 'Allied Adhesives & Hardware' },
];

export const INITIAL_SITES: Omit<Site, 'id'>[] = [
  { name: 'Prestige Lakeside Habitat' },
  { name: 'Sobha Dream Acres' },
  { name: 'Phoenix One Bangalore West' },
];

export const INITIAL_INVENTORY: Omit<InventoryItem, 'id'>[] = [
  { name: 'Plywood (18mm)', unit: 'sheets', quantity: 50, threshold: 20 },
  { name: 'Oak Veneer', unit: 'sq. ft.', quantity: 200, threshold: 100 },
  { name: 'Linen Fabric', unit: 'meters', quantity: 80, threshold: 50 },
  { name: 'Italian Marble', unit: 'sq. ft.', quantity: 30, threshold: 25 },
  { name: 'Wood Glue Agent', unit: 'liters', quantity: 40, threshold: 20 },
  { name: 'High-Density Foam', unit: 'sheets', quantity: 60, threshold: 30 },
  { name: 'Stainless Steel Hinges', unit: 'pieces', quantity: 500, threshold: 200 },
  { name: 'Matte Black Paint', unit: 'liters', quantity: 15, threshold: 10 },
];

// FIX: Wrapped the complex type in parentheses to ensure correct type parsing by TypeScript.
export const INITIAL_ORDERS: (Omit<PurchaseOrder, 'id' | 'vendorId' | 'lineItems'> & { vendorName: string, lineItems: (Omit<OrderLineItem, 'id' | 'materialId'> & { materialName: string })[] })[] = [
    {
        vendorName: 'Royal Timbers Inc.',
        lineItems: [
            {
                materialName: 'Plywood (18mm)',
                quantity: 20,
                unit: 'sheets',
                specifications: 'Grade A, Calibrated, Moisture Resistant',
                size: '8x4 ft',
                brand: 'Greenlam',
                site: 'Prestige Lakeside Habitat',
                rate: 1800,
                gst: 18,
                discount: 500,
                freight: 1200,
            },
            {
                materialName: 'Oak Veneer',
                quantity: 150,
                unit: 'sq. ft.',
                specifications: 'Natural Oak, 4mm thickness',
                rate: 250,
                gst: 18,
            }
        ],
        notes: 'Urgent delivery needed for the Prestige project. Please coordinate with site manager.',
        priority: Priority.High,
        status: OrderStatus.Pending,
        orderedOn: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString().split('T')[0],
        expectedDelivery: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString().split('T')[0],
        raisedBy: 'Priya Sharma',
        autoGenerated: false,
    },
    {
        vendorName: 'Stone World Suppliers',
        lineItems: [
            {
                materialName: 'Italian Marble',
                quantity: 50,
                unit: 'sq. ft.',
                specifications: 'Carrara White Italian Marble, 20mm thickness, polished finish.',
                rate: 1200,
                gst: 28,
                freight: 3000,
            }
        ],
        priority: Priority.Low,
        status: OrderStatus.Delivered,
        orderedOn: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString().split('T')[0],
        expectedDelivery: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString().split('T')[0],
        deliveredOn: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString().split('T')[0],
        raisedBy: 'Ravi Kumar',
        autoGenerated: false,
    }
];


export const INITIAL_ISSUANCES: Omit<MaterialIssuance, 'id'>[] = [];

export const INITIAL_INTENTS: Omit<PurchaseIntent, 'id'>[] = [];