export enum Priority {
  Low = 'Low',
  High = 'High',
  Urgent = 'Urgent',
}

export enum OrderStatus {
  Pending = 'Pending',
  AwaitingApproval = 'Awaiting Approval',
  Delivered = 'Delivered',
  Cancelled = 'Cancelled',
}

export enum PurchaseIntentStatus {
    Pending = 'Pending Review',
    Approved = 'Approved for PO',
    Rejected = 'Rejected',
    Converted = 'PO Created',
}

export interface User {
  id: string;
  name: string;
  role: 'manager' | 'purchaser' | 'inventory_manager';
}

export interface Material {
  id: string;
  name: string;
  unit: string;
  created_at?: string;
}

export interface Vendor {
  id: string;
  name: string;
  created_at?: string;
}

export interface Site {
  id: string;
  name: string;
  created_at?: string;
}

export interface InventoryItem {
  id: string; // Corresponds to Material ID
  name: string;
  unit: string;
  quantity: number;
  threshold: number;
  created_at?: string;
}

export interface OrderLineItem {
  id: string;
  orderId?: string;
  materialId: string;
  quantity: number;
  unit: string;
  specifications: string;
  size?: string;
  brand?: string;
  site?: string;
  rate: number;
  gst: number;
  discount?: number;
  freight?: number;
  created_at?: string;
}

export interface PurchaseOrder {
  id: string;
  vendorId: string;
  lineItems: OrderLineItem[];
  notes?: string;
  priority: Priority;
  status: OrderStatus;
  orderedOn: string; // YYYY-MM-DD
  expectedDelivery: string; // YYYY-MM-DD
  deliveredOn?: string; // YYYY-MM-DD
  raisedBy: string;
  autoGenerated: boolean;
  approvedBy?: string;
  approvedOn?: string;
  rejectedBy?: string;
  rejectedOn?: string;
  rejectionReason?: string;
  receivedBy?: string;
  intentId?: string;
  created_at?: string;
}

export interface MaterialIssuance {
  id: string;
  materialId: string;
  quantity: number;
  unit: string;
  issuedToSite: string;
  issuedBy: string;
  issuedOn: string; // YYYY-MM-DD
  notes?: string;
  created_at?: string;
}

export interface PurchaseIntentLineItem {
  id: string;
  intentId?: string;
  materialId: string;
  quantity: number;
  unit: string;
  site?: string;
  notes?: string;
  created_at?: string;
}

export interface PurchaseIntent {
  id: string;
  lineItems: PurchaseIntentLineItem[];
  notes?: string;
  requestedBy: string;
  requestedOn: string; // YYYY-MM-DD
  status: PurchaseIntentStatus;
  reviewedBy?: string;
  reviewedOn?: string;
  rejectionReason?: string;
  created_at?: string;
}

export interface AppNotification {
  id: number;
  type: 'success' | 'warning' | 'danger' | 'info';
  message: string;
}

export interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}