
export enum Priority {
  Low = 'Low',
  High = 'High',
  Urgent = 'Urgent',
}

export enum OrderStatus {
  Pending = 'Pending',
  AwaitingApproval = 'Awaiting Approval',
  Delivered = 'Delivered',
  Cancelled = 'Cancelled',
}

export enum PurchaseIntentStatus {
  Pending = 'Pending Review',
  Approved = 'Approved for PO',
  Rejected = 'Rejected',
  Converted = 'PO Created',
}

export interface User {
  uid: string;
  name: string | null;
  email: string | null;
  role: 'purchaser' | 'manager' | 'inventory_manager';
}

export interface Vendor {
  id: string;
  name: string;
}

export interface Material {
  id: string;
  name: string;
  unit: string;
}

export interface Site {
  id: string;
  name: string;
}

export interface InventoryItem extends Material {
  quantity: number;
  threshold: number;
}

export interface OrderLineItem {
  id: string; // Unique ID for the line item itself (e.g., for React keys)
  // FIX: Added optional orderId to link line item to a purchase order.
  orderId?: string;
  materialId: string;
  specifications: string;
  quantity: number;
  size?: string;
  unit: string;
  brand?: string;
  site?: string;
  rate: number;
  discount?: number;
  gst: number;
  freight?: number;
}


export interface PurchaseOrder {
  id: string; // PO Number / Firestore Doc ID
  vendorId: string;
  lineItems: OrderLineItem[];
  notes?: string;
  priority: Priority;
  status: OrderStatus;
  orderedOn: string;
  expectedDelivery: string;
  deliveredOn?: string;
  receivedBy?: string;
  raisedBy: string;
  autoGenerated: boolean;
  approvedBy?: string;
  approvedOn?: string;
  rejectedBy?: string;
  rejectedOn?: string;
  rejectionReason?: string;
  intentId?: string; // Link back to the original intent
}

export interface PurchaseIntentLineItem {
  id: string; // for React keys
  // FIX: Added optional intentId to link line item to a purchase intent.
  intentId?: string;
  materialId: string;
  quantity: number;
  unit: string;
  site?: string;
  notes?: string; // Specific notes for this item
}

export interface PurchaseIntent {
  id: string;
  lineItems: PurchaseIntentLineItem[]; // Replaces single material fields
  notes?: string; // Overall reason for the request
  requestedBy: string;
  requestedOn: string;
  status: PurchaseIntentStatus;
  reviewedBy?: string;
  reviewedOn?: string;
  rejectionReason?: string;
}

export interface MaterialIssuance {
  id: string;
  materialId: string;
  quantity: number;
  unit: string;
  issuedToSite: string;
  issuedBy: string;
  issuedOn: string;
  notes?: string;
}

export interface AppNotification {
  id: number;
  type: 'success' | 'warning' | 'info';
  message: string;
}

// FIX: Added Translations type definition to resolve import error in translations.ts
export type Translations = {
  [key: string]: {
    [key:string]: string;
  };
};