
import React, { useState, useEffect } from 'react';
import { PurchaseOrder, Vendor, Priority, OrderStatus, OrderLineItem, Material, Site, User } from '../types';
import { UNITS } from '../constants';
// FIX: Corrected icon import path to resolve file casing issue.
import { PlusIcon, TrashIcon } from './Icons';

interface NewOrderFormProps {
  onAddOrder: (order: Omit<PurchaseOrder, 'id'>) => void;
  onClose: () => void;
  currentUser: string;
  currentUserRole: User['role'];
  vendors: Vendor[];
  materials: Material[];
  sites: Site[];
  initialData?: Partial<PurchaseOrder>;
}

const NewOrderForm: React.FC<NewOrderFormProps> = ({ onAddOrder, onClose, currentUser, currentUserRole, vendors, materials, sites, initialData }) => {
  const [vendorId, setVendorId] = useState<string>(initialData?.vendorId?.toString() || '');
  const [priority, setPriority] = useState<Priority>(initialData?.priority || Priority.Low);
  const [expectedDelivery, setExpectedDelivery] = useState<string>('');
  const [notes, setNotes] = useState(initialData?.notes || '');
  const [lineItems, setLineItems] = useState<Partial<OrderLineItem>[]>(initialData?.lineItems || [{}]);
  
  useEffect(() => {
    // Set a default delivery date if not provided by initialData
    if (!initialData?.expectedDelivery) {
        setExpectedDelivery(new Date(new Date().setDate(new Date().getDate() + 7)).toISOString().split('T')[0]);
    } else {
        setExpectedDelivery(initialData.expectedDelivery);
    }
  }, [initialData]);

  const handleLineItemChange = (index: number, field: keyof OrderLineItem, value: any) => {
    const updatedLineItems = [...lineItems];
    updatedLineItems[index] = { ...updatedLineItems[index], [field]: value };
    
    if (field === 'materialId') {
        const material = materials.find(m => m.id === value);
        if (material) {
            updatedLineItems[index].unit = material.unit;
        }
    }
    
    setLineItems(updatedLineItems);
  };

  const addLineItem = () => setLineItems([...lineItems, {}]);
  const removeLineItem = (index: number) => {
    if (lineItems.length > 1) {
      setLineItems(lineItems.filter((_, i) => i !== index));
    }
  };

  const calculateLineTotal = (item: Partial<OrderLineItem>) => {
    const quantity = Number(item.quantity) || 0;
    const rate = Number(item.rate) || 0;
    const discountPercent = Number(item.discount) || 0;
    const gst = Number(item.gst) || 0;
    const freight = Number(item.freight) || 0;

    const grossAmount = quantity * rate;
    const discountAmount = grossAmount * (discountPercent / 100);
    const subTotal = grossAmount - discountAmount;
    const gstAmount = subTotal * (gst / 100);
    return subTotal + gstAmount + freight;
  };

  const totalInvoiceAmount = lineItems.reduce((total, item) => total + calculateLineTotal(item), 0);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!vendorId) {
      alert("Please select a vendor.");
      return;
    }
    
    const finalLineItems = lineItems.filter(item => item.materialId && item.quantity && item.rate).map(item => ({
        ...item,
        id: `LI-${Date.now()}-${Math.random()}`,
        materialId: item.materialId as string,
        quantity: Number(item.quantity),
        rate: Number(item.rate),
        discount: item.discount ? Number(item.discount) : undefined,
        gst: Number(item.gst || 18),
        freight: item.freight ? Number(item.freight) : undefined,
    })) as OrderLineItem[];

    if (finalLineItems.length === 0) {
        alert("Please add at least one valid material item to the order.");
        return;
    }
    
    const isManager = currentUserRole === 'manager';

    const newOrder: Omit<PurchaseOrder, 'id'> = {
      vendorId: vendorId,
      lineItems: finalLineItems,
      notes,
      priority,
      status: isManager ? OrderStatus.Pending : OrderStatus.AwaitingApproval,
      orderedOn: new Date().toISOString().split('T')[0],
      expectedDelivery,
      raisedBy: currentUser,
      autoGenerated: false,
      intentId: initialData?.intentId,
    };
    onAddOrder(newOrder);
    onClose();
  };

  const inputClasses = "w-full bg-gray-100 border-gray-300 rounded-md p-2 text-gray-800 focus:ring-2 focus:ring-primary-500 focus:border-primary-500 transition shadow-sm";
  const smallInputClasses = `text-sm ${inputClasses}`;
  const labelClasses = "block mb-1.5 text-sm font-medium text-gray-600";
  const smallLabelClasses = "block mb-1 text-xs font-medium text-gray-500";


  return (
    <form onSubmit={handleSubmit} className="space-y-8">
      {/* Order Header */}
      <div className="space-y-4">
        <h3 className="text-lg font-semibold text-gray-800 border-b pb-2">Order Details</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
                <label className={labelClasses}>Vendor</label>
                <select value={vendorId} onChange={e => setVendorId(e.target.value)} className={inputClasses} required>
                    <option value="">Select Vendor</option>
                    {vendors.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}
                </select>
            </div>
            <div>
                <label className={labelClasses}>Priority</label>
                <select value={priority} onChange={e => setPriority(e.target.value as Priority)} className={inputClasses}>
                    {Object.values(Priority).map(p => <option key={p} value={p}>{p}</option>)}
                </select>
            </div>
            <div>
                <label className={labelClasses}>Expected Delivery</label>
                <input type="date" value={expectedDelivery} onChange={e => setExpectedDelivery(e.target.value)} className={inputClasses} min={new Date().toISOString().split('T')[0]} required />
            </div>
        </div>
        <div>
            <label className={labelClasses}>Notes</label>
            <textarea value={notes} onChange={e => setNotes(e.target.value)} className={`${inputClasses} min-h-[80px]`} placeholder="Any overall notes for this purchase order..."></textarea>
        </div>
      </div>

      {/* Line Items */}
      <div className="space-y-4">
        <h3 className="text-lg font-semibold text-gray-800 border-b pb-2">Order Items</h3>
        {lineItems.map((item, index) => (
          <div key={index} className="p-5 bg-gray-50 rounded-lg space-y-4 relative border border-gray-200">
             <button type="button" onClick={() => removeLineItem(index)} className="absolute top-2 right-2 bg-red-100 text-red-600 rounded-full p-1 hover:bg-red-200 disabled:bg-gray-200 disabled:text-gray-400" disabled={lineItems.length <= 1} title="Remove Item">
                <TrashIcon className="w-4 h-4" />
            </button>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                 <div>
                    <label className={smallLabelClasses}>Material</label>
                    <select value={item.materialId || ''} onChange={e => handleLineItemChange(index, 'materialId', e.target.value)} className={smallInputClasses} required>
                        <option value="">Select Material</option>
                         {materials.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}
                    </select>
                </div>
                <div>
                    <label className={smallLabelClasses}>Brand</label>
                    <input type="text" value={item.brand || ''} onChange={e => handleLineItemChange(index, 'brand', e.target.value)} placeholder="e.g., Greenlam" className={smallInputClasses} />
                </div>
                <div>
                    <label className={smallLabelClasses}>Site / Client</label>
                    <input 
                        type="text" 
                        value={item.site || ''} 
                        onChange={e => handleLineItemChange(index, 'site', e.target.value)} 
                        placeholder="e.g., Project Name" 
                        className={smallInputClasses}
                        list="sites-list"
                    />
                    <datalist id="sites-list">
                        {sites.map(site => <option key={site.id} value={site.name} />)}
                    </datalist>
                </div>
            </div>

            <div>
                <label className={smallLabelClasses}>Specifications</label>
                <textarea value={item.specifications || ''} onChange={e => handleLineItemChange(index, 'specifications', e.target.value)} className={`${smallInputClasses} min-h-[60px]`} placeholder="e.g., Grade A, termite resistant..."></textarea>
            </div>
            
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                 <div>
                    <label className={smallLabelClasses}>Quantity</label>
                    <input type="number" value={item.quantity || ''} onChange={e => handleLineItemChange(index, 'quantity', e.target.value)} placeholder="0" min="1" className={smallInputClasses} required/>
                </div>
                 <div>
                    <label className={smallLabelClasses}>Unit</label>
                     <select value={item.unit || ''} onChange={e => handleLineItemChange(index, 'unit', e.target.value)} className={smallInputClasses}>
                        {UNITS.map(u => <option key={u} value={u}>{u}</option>)}
                    </select>
                </div>
                 <div>
                    <label className={smallLabelClasses}>Size</label>
                    <input type="text" value={item.size || ''} onChange={e => handleLineItemChange(index, 'size', e.target.value)} placeholder="e.g., 8x4 ft" className={smallInputClasses} />
                </div>
                <div>
                    <label className={smallLabelClasses}>Rate per Unit</label>
                    <input type="number" value={item.rate || ''} onChange={e => handleLineItemChange(index, 'rate', e.target.value)} placeholder="0.00" min="0" step="0.01" className={smallInputClasses} required/>
                </div>
            </div>

            <div className="grid grid-cols-2 md:grid-cols-5 gap-4 items-end pt-4 border-t border-gray-200">
                <div>
                    <label className={smallLabelClasses}>Discount %</label>
                    <input type="number" value={item.discount || ''} onChange={e => handleLineItemChange(index, 'discount', e.target.value)} placeholder="0" min="0" max="100" className={smallInputClasses} />
                </div>
                <div>
                    <label className={smallLabelClasses}>GST %</label>
                    <input type="number" value={item.gst || ''} onChange={e => handleLineItemChange(index, 'gst', e.target.value)} placeholder="18" className={smallInputClasses} />
                </div>
                <div>
                    <label className={smallLabelClasses}>Freight</label>
                    <input type="number" value={item.freight || ''} onChange={e => handleLineItemChange(index, 'freight', e.target.value)} placeholder="0.00" className={smallInputClasses} />
                </div>
                <div className="md:col-span-2 text-right">
                    <label className={smallLabelClasses}>Item Total</label>
                    <p className="font-semibold text-xl text-gray-800">₹{calculateLineTotal(item).toFixed(2)}</p>
                </div>
            </div>
          </div>
        ))}
      </div>
        
      <button type="button" onClick={addLineItem} className="w-full flex items-center justify-center gap-2 py-2.5 bg-gray-100 hover:bg-gray-200 rounded-md text-gray-700 font-medium transition border border-gray-300">
        <PlusIcon className="w-5 h-5" /> Add Another Material
      </button>

      {/* Footer */}
       <div className="flex justify-between items-center pt-6 border-t border-gray-200">
        <div>
            <span className="text-sm font-medium text-gray-600">Total Invoice Amount:</span>
            <p className="font-bold text-3xl text-gray-900 tracking-tight">₹{totalInvoiceAmount.toFixed(2)}</p>
        </div>
        <div className="flex justify-end gap-3">
            <button type="button" onClick={onClose} className="px-5 py-2.5 bg-white border border-gray-300 hover:bg-gray-100 rounded-md text-gray-800 font-semibold transition">Close</button>
            <button type="submit" className="px-6 py-2.5 bg-primary-600 hover:bg-primary-700 rounded-md text-white font-semibold transition shadow-sm">
                {currentUserRole === 'manager' ? 'Submit Order' : 'Submit for Approval' }
            </button>
        </div>
      </div>
    </form>
  );
};

export default NewOrderForm;