import React from 'react';
import { PurchaseOrder, Vendor, OrderStatus, Priority, Material } from '../types';
import Modal from './Modal';

interface OrderDetailsModalProps {
  isOpen: boolean;
  onClose: () => void;
  order: PurchaseOrder;
  vendors: Vendor[];
  materials: Material[];
}

const OrderDetailsModal: React.FC<OrderDetailsModalProps> = ({ isOpen, onClose, order, vendors, materials }) => {
  const vendor = vendors.find(v => v.id === order.vendorId);

  const getPriorityClass = (priority: Priority) => {
    switch (priority) {
      case Priority.Urgent: return 'bg-red-100 text-red-700';
      case Priority.High: return 'bg-amber-100 text-amber-700';
      case Priority.Low: return 'bg-blue-100 text-blue-700';
      default: return 'bg-gray-100 text-gray-700';
    }
  };

  const getStatusClass = (status: OrderStatus) => {
    switch (status) {
      case OrderStatus.Delivered: return 'bg-green-100 text-green-700';
      case OrderStatus.Pending: return 'bg-yellow-100 text-yellow-700';
      case OrderStatus.AwaitingApproval: return 'bg-sky-100 text-sky-700';
      case OrderStatus.Cancelled: return 'bg-gray-100 text-gray-700';
      default: return 'bg-gray-100 text-gray-700';
    }
  };

  const calculateLineTotal = (item: { quantity: number; rate: number; discount?: number; gst: number; freight?: number; }) => {
    const grossAmount = item.quantity * item.rate;
    const discountAmount = grossAmount * ((item.discount || 0) / 100);
    const subTotal = grossAmount - discountAmount;
    const gstAmount = subTotal * (item.gst / 100);
    return subTotal + gstAmount + (item.freight || 0);
  };
  
  const totalInvoiceAmount = order.lineItems.reduce((total, item) => total + calculateLineTotal(item), 0);

  return (
    <Modal isOpen={isOpen} onClose={onClose} title={`Order Details: ${order.id}`}>
      <div className="space-y-6">
        {/* Header Info */}
        <div className="p-5 bg-gray-50 rounded-lg border border-gray-200">
            <div className="flex justify-between items-start mb-4">
                <div>
                    <h3 className="text-lg font-semibold text-gray-800">{vendor?.name}</h3>
                    <p className="text-sm text-gray-500">Raised by: {order.raisedBy} on <span className="font-mono">{order.orderedOn}</span></p>
                </div>
                 <div className="flex flex-col items-end gap-2">
                    <span className={`px-2.5 py-1 text-xs font-medium rounded-full ${getStatusClass(order.status)}`}>
                        {order.autoGenerated && order.status === OrderStatus.Pending ? 'Auto-Generated' : order.status}
                    </span>
                    <span className={`px-2.5 py-1 text-xs font-medium rounded-full ${getPriorityClass(order.priority)}`}>
                        {order.priority} Priority
                    </span>
                 </div>
            </div>
            <dl className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm border-t border-gray-200 pt-4">
                <div>
                    <dt className="font-medium text-gray-500">Expected Delivery</dt>
                    <dd className="text-gray-900 font-mono mt-0.5">{order.expectedDelivery}</dd>
                </div>
                {order.deliveredOn && (
                     <div>
                        <dt className="font-medium text-gray-500">Delivered On</dt>
                        <dd className="text-gray-900 font-mono mt-0.5">{order.deliveredOn}</dd>
                    </div>
                )}
                {order.receivedBy && (
                     <div>
                        <dt className="font-medium text-gray-500">Received By</dt>
                        <dd className="text-gray-900 font-medium mt-0.5">{order.receivedBy}</dd>
                    </div>
                )}
            </dl>
        </div>
        
        {/* Approval/Rejection Info */}
        {(order.approvedBy || order.rejectedBy) && (
            <div>
                <h4 className="text-base font-semibold text-gray-700 mb-2">Approval Status</h4>
                <div className="p-4 bg-gray-50 rounded-lg border border-gray-200 text-sm space-y-1">
                    {order.approvedBy && (
                        <p className="text-green-700">Approved by <span className="font-semibold">{order.approvedBy}</span> on <span className="font-mono">{order.approvedOn}</span></p>
                    )}
                    {order.rejectedBy && (
                        <p className="text-red-700">Rejected by <span className="font-semibold">{order.rejectedBy}</span> on <span className="font-mono">{order.rejectedOn}</span></p>
                    )}
                    {order.rejectionReason && (
                        <div className="pt-1">
                            <p className="text-gray-600"><span className="font-semibold">Reason:</span> {order.rejectionReason}</p>
                        </div>
                    )}
                </div>
            </div>
        )}

        {/* Line Items Table */}
        <div>
            <h4 className="text-base font-semibold text-gray-700 mb-2">Order Items</h4>
            <div className="overflow-x-auto border border-gray-200 rounded-lg">
                <table className="w-full text-left text-sm">
                    <thead className="bg-gray-50">
                        <tr className="border-b border-gray-200">
                            <th className="p-3 font-semibold text-gray-600">Material</th>
                            <th className="p-3 font-semibold text-gray-600 text-right">Qty</th>
                            <th className="p-3 font-semibold text-gray-600 text-right">Rate</th>
                            <th className="p-3 font-semibold text-gray-600 text-right">GST%</th>
                            <th className="p-3 font-semibold text-gray-600 text-right">Total</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200">
                        {order.lineItems.map(item => {
                            const material = materials.find(m => m.id === item.materialId);
                            return(
                                <tr key={item.id}>
                                    <td className="p-3 align-top">
                                        <div className="font-medium text-gray-800">{material?.name}</div>
                                        {item.specifications && <div className="text-xs text-gray-500 mt-1">{item.specifications}</div>}
                                        <div className="flex gap-4 text-xs text-gray-500 mt-1">
                                            {item.brand && <span>Brand: <span className="font-medium">{item.brand}</span></span>}
                                            {item.site && <span>Site: <span className="font-medium">{item.site}</span></span>}
                                            {item.discount && item.discount > 0 && <span>Discount: <span className="font-medium">{item.discount}%</span></span>}
                                        </div>
                                    </td>
                                    <td className="p-3 text-right font-mono align-top">{item.quantity} {item.unit}</td>
                                    <td className="p-3 text-right font-mono align-top">₹{item.rate.toFixed(2)}</td>
                                    <td className="p-3 text-right font-mono align-top">{item.gst}%</td>
                                    <td className="p-3 text-right font-mono font-semibold text-gray-800 align-top">₹{calculateLineTotal(item).toFixed(2)}</td>
                                </tr>
                            )
                        })}
                    </tbody>
                </table>
            </div>
        </div>

        {order.notes && (
            <div>
                <h4 className="text-sm font-semibold text-gray-600 mb-1">Notes</h4>
                <p className="p-3 bg-gray-50 rounded-md text-gray-700 whitespace-pre-wrap text-sm border border-gray-200">{order.notes}</p>
            </div>
        )}

        {/* Total and Close button */}
        <div className="flex justify-between items-center pt-6 border-t border-gray-200">
            <div>
                 <span className="text-sm font-medium text-gray-600">Total Invoice Amount:</span>
                 <p className="font-bold text-3xl text-gray-900 tracking-tight">₹{totalInvoiceAmount.toFixed(2)}</p>
            </div>
            <button
            type="button"
            onClick={onClose}
            className="px-5 py-2.5 bg-primary-600 hover:bg-primary-700 rounded-md text-white font-semibold transition shadow-sm"
            >
            Close
            </button>
        </div>
      </div>
    </Modal>
  );
};

export default OrderDetailsModal;